name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_SECRET }}
    - name: Pull previous version
      run: docker pull ghcr.io/logicfox/external-mdns:test
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm/v7,linux/amd64,linux/arm64 --file Dockerfile . --tag ghcr.io/logicfox/external-mdns:$(date +%s) --tag ghcr.io/logicfox/external-mdns:latest --push
