name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: blake/external-mdns.git
        ref: master
    - name: Build the Docker image
      run: docker buildx build --platform armhf --file Dockerfile . --tag ghcr.io/logicfox/external-mdns:armhf-$(date +%s)
